---
title: "Habituals: speaker (truth judgments)"
output: html_notebook
---
```{r}
knitr::opts_chunk$set(echo=FALSE, warning=FALSE, message=FALSE)
```


```{r}
library(langcog)
library(tidyr)
library(dplyr)
library(data.table)
library(coda)
library(knitr)
library(ggthemes)
library(rwebppl)
theme_set(theme_few())
estimate_mode <- function(s) {
  d <- density(s)
  return(d$x[which.max(d$y)])
}
hdi_upper<- function(s){
  m <- HPDinterval(mcmc(s))
  return(m["var1","upper"])
}
hdi_lower<- function(s){
  m <- HPDinterval(mcmc(s))
  return(m["var1","lower"])
}
betaMean = function(a, b){
  return ( a / (a + b ))
}

betaSDev = function(a, b){
  return( sqrt ( ( a * b) / ( ( a + b ) ^ 2 * (a + b + 1) ) ) ) 
}
project.path <- "~/Documents/research/generics-paper/"
data.path <- "models/habituals/data/"
model.path <- "models/habituals/"
```

Load truth judgment data

```{r}
d.hab <- read.csv(paste(project.path, data.path, 
                    "tj-2-logtimes.csv", sep = ""))

d.hab.summary <- d.hab %>% 
  mutate(response = ifelse(response == "agree-key", 1, 0),
         roundedFreq = round(log_times * 2) / 2) %>%
  group_by(habitual, time_period, log_times, roundedFreq) %>%
  multi_boot_standard(column = "response")
```


```{r}
n_chains <- 3
n_samples <- 100000
burn <- n_samples / 2
lag <- 20
#model_prefix <- "results-habituals-s1-smtncshabitual-"
#model_prefix <- "results-habituals-smtncshabitual-"
#model_prefix <- "results-habituals-S1-cdfPrior-"
#model_prefix <- "results-habituals-S1-ffPriorDirScaling-oppositeAlt-"
#model_prefix <- "results-habituals-S1-ffPriorDirNoScaling-silenceAltCost-"
model_prefix <- "results-habituals-S2-ffPriorDirScaling-silenceAlt-"
#model_prefix <- "results-habituals-S1-ffPriorDirScaling-oppositeAlt-"
#model_prefix <- "results-fullModel-s1-smtncsgeneric-"
#model_prefix <- "results-fullModel-bernprior-smtncsgeneric-"
#model_prefix <- "results-fullModel-smtncsmost-"
m.samp <- data.frame()
for (i in seq(1, n_chains)){
  mi <- fread(paste(project.path, model.path,
                    "results/",
                    model_prefix, n_samples, "_burn", burn, "_lag", lag,
                    "_chain", i, ".csv", sep = ""))

  m.samp.i <- mi %>% mutate(chain = i)
  m.samp <- bind_rows(m.samp, m.samp.i)
  print(i)
}

#n_samples <- 10000

#m.samp <- fread(paste(project.path, model.path, "results/results-habituals-S1-ffPriorDir-oppositeAlt-100000_burn50000_lag25_chain1.csv", sep  = ""))
#
#m.samp <- get_samples(m.samp, n_samples) 
```

### Parameter posteriors

```{r}
m.samp %>% 
  filter(type == "param") %>% 
  #mutate(chain = 0) %>%
  # rename(s1opt = mix_male_b, s2opt = mix_female_b,
  #        null_mu = freq_male_sigma, null_sigma = freq_female_sigma) %>%
  #gather(key, val, s1opt, s2opt, null_mu, null_sigma) %>%
  ggplot(., aes(x = val, fill = factor(chain)))+
  geom_histogram(position = position_dodge())+
  facet_wrap(~ item + cat, scales = 'free')
```

## Priors

```{r fig.width = 12, fig.height = 12}
m.samp %>%
  filter(type == "prior") %>%
  group_by(item, param) %>%
  summarise(MAP = estimate_mode(val),
            credUpper = hdi_upper(val),
            credLower = hdi_lower(val)) %>%
  ggplot(., aes(x = to.n(param), y = MAP, ymin = credLower, ymax = credUpper))+
  geom_bar(stat = 'identity', position = position_dodge())+
  geom_errorbar(position = position_dodge())+
  facet_wrap(~item)
```



## Posterior predictive -- truth judgments

```{r}
m.pp <- m.samp %>%
  filter(type == "predictive") %>%
  rename(habitual = item, 
         time_period = param) %>% 
  #mutate(roundedFreq = factor(as.numeric(roundedFreq))) %>%
  group_by(habitual, time_period, chain) %>%
  #group_by(habitual, time_period) %>%
  summarize(MAP = estimate_mode(val),
            cred_upper = hdi_upper(val),
            cred_lower = hdi_lower(val))

md <- left_join(m.pp, 
                d.hab.summary %>% ungroup())#%>% mutate(roundedFreq = factor(roundedFreq)))
```

```{r}
ggplot(md, aes(x = MAP, xmin = cred_lower, xmax = cred_upper,
               y = mean, ymin = ci_lower, ymax = ci_upper))+
  geom_point()+
  xlim(0, 1)+
  ylim(0, 1)+
  geom_abline(intercept = 0, slope = 1, lty = 3)+
  geom_errorbar(alpha = 0.2)+
  geom_errorbarh(alpha = 0.2)+
  coord_fixed() +
  facet_wrap(~chain)
```


### Error analysis (individual chains)

```{r}

m.pp2 <- m.samp %>%
  filter(type == "predictive") %>%
  rename(habitual = item, 
         time_period = param) %>% 
  group_by(habitual, time_period) %>%
  summarize(MAP = estimate_mode(val),
            cred_upper = hdi_upper(val),
            cred_lower = hdi_lower(val))

md <- left_join(m.pp, 
                d.hab.summary %>% ungroup())

```
```{r}
mm.2 <- left_join(m.pp, 
                  m.pp2 %>%
                    rename(wSoftmax = MAP,
                           wSoft_high = cred_upper,
                           sSoft_low = cred_lower))

ggplot(mm.2, aes(x = MAP, xmin = cred_lower, xmax = cred_upper,
               y = wSoftmax, ymin = sSoft_low, ymax = wSoft_high))+
  geom_point()+
  xlim(0, 1)+
  ylim(0, 1)+
  geom_abline(intercept = 0, slope = 1, lty = 3)+
  geom_errorbar(alpha = 0.2)+
  geom_errorbarh(alpha = 0.2)+
  coord_fixed() 
```


$$r^2 = `r with(md, cor(MAP, mean))^2`$$
$$MSE = `r with(md, mean(sqErr))`$$

```{r}
md <- md %>%
  mutate(sqErr = (MAP-mean)^2)

md[with(md, order(-sqErr)), ] %>% head(20) %>% 
  select(habitual, time_period, MAP, mean, sqErr) %>% kable()
```

### Error analysis (collapsing chains)
```{r}
md <- left_join(m.samp %>%
  filter(type == "predictive") %>%
  rename(habitual = item, 
         time_period = param) %>% 
  group_by(habitual, time_period) %>%
  summarize(MAP = estimate_mode(val),
            cred_upper = hdi_upper(val),
            cred_lower = hdi_lower(val)),
                d.hab.summary %>% ungroup()) %>%
  mutate(sqErr = (MAP-mean)^2)
```

$$MSE = `r with(md, mean(sqErr))`$$

$$r^2 = `r with(md, cor(MAP, mean))^2`$$

```{r}
md[with(md, order(-sqErr)), ] %>% head(20) %>% 
  select(habitual, time_period, MAP, mean, sqErr) %>% 
  kable()
```


## Propensity priors

Load prior data

```{r fig.height = 8, fig.width = 6}
d.hab.prior.e <- read.csv(paste(project.path, data.path, 
                      "prior2-existence.csv", sep = ""))

d.hab.prior.e <- d.hab.prior.e %>% 
  mutate(avoided_endval = ifelse(val==1, 0.999,
                                 ifelse(val==0, 0.001, val)))


d.hab.prior.f <- read.csv(paste(project.path, data.path, 
                      "prior2-timesper5yr.csv", sep = "")) %>%
  mutate(log_dayRate = log(val / (365*5)))


# ggplot(d.hab.prior.f, aes( x= log(val / (365*5)) ))+
#   geom_histogram(position = position_dodge())
# 
# ggplot(d.hab.prior.f, aes( x= log(val / (365*5)), fill = gender ))+
#   geom_histogram(position = position_dodge())+
#   facet_wrap(~item)
```


Raw prior data

```{r  fig.height = 8, fig.width = 6, eval = F}
dh.prior <- read.csv("/Users/mht/Documents/research/habituals/data/priors/priors-2.csv")

dh.prior <- dh.prior %>%
  mutate(comparisonTime_men = as.character(comparisonTime_men),
         comparisonTime_women = as.character(comparisonTime_women)) %>%
  rowwise() %>%
  mutate(
    mixture_male = nPersons_men / comparisonNum_men,
    mixture_female = nPersons_women / comparisonNum_women,
    dayRate_male = ifelse(comparisonTime_men == "week", nInstances_men / 7,
                   ifelse(comparisonTime_men == "month", nInstances_men / 30,
                   ifelse(comparisonTime_men == "year", nInstances_men / 365,
                   ifelse(comparisonTime_men == "5 years", 
                          nInstances_men / (5*365), -99)))),
    dayRate_female = ifelse(comparisonTime_women == "week", nInstances_women / 7,
                   ifelse(comparisonTime_women == "month", nInstances_women / 30,
                   ifelse(comparisonTime_women == "year", nInstances_women / 365,
                   ifelse(comparisonTime_women == "5 years", 
                          nInstances_women / (5*365), -99)))),
    annualRate_male = dayRate_male * 365,
    annualRate_female = dayRate_female * 365
  )


dh.prior.filtered <- filter(dh.prior, 
       !(
         (mixture_male == 0) ||   (mixture_female == 0) ||   
           (dayRate_male == 0) ||   (dayRate_female == 0)  )
       )

# ggplot(dh.prior.filtered %>% 
#          select(item, starts_with("dayRate")) %>%
#          gather(key, val, -item), aes( x= log(val )))+
#   geom_histogram(position = position_dodge())+
#   facet_wrap(~item, scales = 'free')

write.csv(dh.prior, file = paste(project.path, data.path, "prior2.csv", sep = ""))
```


#### Model posteriors on prior parameter

```{r fig.width = 12, fig.height = 5, eval = F}
m.samp %>%
  filter(param == "prior") %>% 
  group_by(item) %>%
  sample_n(1000) %>%
  ungroup() %>%
  mutate(mix_male_a = as.numeric(mix_male_a),
         mix_female_a = as.numeric(mix_female_a),
         freq_male_mu = as.numeric(freq_male_mu), 
         freq_female_mu = as.numeric(freq_female_mu)) %>%
  rowwise() %>%
  mutate(mix_male_mean = betaMean(mix_male_a, mix_male_b),
         mix_male_stdev = betaSDev(mix_male_a, mix_male_b),
         mix_female_mean = betaMean(mix_female_a, mix_female_b),
         mix_female_stdev = betaSDev(mix_female_a, mix_female_b)
         ) %>% 
  ungroup() %>%
  select(-param, -ends_with("_a"), -ends_with("_b")) %>%
  gather(key, val, -item) %>% 
  separate(key, into = c("component", "gender", "param")) %>% 
  ggplot(., aes( x = val, fill = gender))+
  geom_histogram(position = position_dodge())+
  scale_fill_solarized()+
  facet_grid(item ~ component + param, scales = 'free')+
  theme(strip.text.y = element_text(angle = 0))


#ggsave("~/Desktop/s2_habituals_priors_170326.pdf", height = 14, width = 8)
```

### Collapsed across chains 

```{r fig.width = 8, fig.height = 12}
bind_rows(
  d.hab.prior.e %>%
    mutate(src = 'data') %>%
    select(-workerid, -category, -metric, -val) %>%
    rename(val = avoided_endval),
  m.samp %>%
    filter(param == "mixture") %>%
    mutate(src = 'model') %>%
    select(-chain, -param, -type)
) %>% ggplot(., aes( x = val, lty = src, color = gender))+
  stat_ecdf()+
  facet_wrap(~item)+
  scale_color_solarized()+
  scale_x_continuous(limits = c(0,1), breaks = c(0, 0.5, 1)) +
  scale_y_continuous(limits = c(0,1), breaks = c(0, 0.5, 1)) +
  theme(strip.text.y = element_text(angle = 0))
```


```{r fig.width = 8, fig.height = 12}

bind_rows(
  d.hab.prior.f %>%
    mutate(src = 'data') %>%
    select(-category, -key, -log_dayRate) %>%
    rename(val = logval),
  m.samp %>%
    filter(param == "frequency") %>%
    mutate(src = 'model') %>%
    select(-chain, -param, -type)
) %>% ggplot(., aes( x = val, lty = src, color = gender))+
  stat_ecdf()+
  facet_wrap(~item)+
  scale_color_solarized()+
  scale_y_continuous(limits = c(0,1), breaks = c(0, 0.5, 1)) +
  theme(strip.text.y = element_text(angle = 0))



#ggsave("~/Desktop/s2_habituals_frequency_cdf.pdf", width = 8, height = 14)
```

### Independent chains

```{r fig.width = 8, fig.height = 12}
bind_rows(
  d.hab.prior.e %>%
    mutate(src = 'data') %>%
    select(-workerid, -category, -metric, -val) %>%
    rename(val = avoided_endval),
  m.samp %>%
    filter(param == "mixture", chain == 1) %>%
    mutate(src = 'model') %>%
    select(-chain, -param, -type)
) %>% ggplot(., aes( x = val, lty = src, color = gender))+
  stat_ecdf()+
  facet_wrap(~item)+
  scale_color_solarized()+
  scale_x_continuous(limits = c(0,1), breaks = c(0, 0.5, 1)) +
  scale_y_continuous(limits = c(0,1), breaks = c(0, 0.5, 1)) +
  theme(strip.text.y = element_text(angle = 0))



bind_rows(
  d.hab.prior.e %>%
    mutate(src = 'data') %>%
    select(-workerid, -category, -metric, -val) %>%
    rename(val = avoided_endval),
  m.samp %>%
    filter(param == "mixture", chain == 2) %>%
    mutate(src = 'model') %>%
    select(-chain, -param, -type)
) %>% ggplot(., aes( x = val, lty = src, color = gender))+
  stat_ecdf()+
  facet_wrap(~item)+
  scale_color_solarized()+
  scale_x_continuous(limits = c(0,1), breaks = c(0, 0.5, 1)) +
  scale_y_continuous(limits = c(0,1), breaks = c(0, 0.5, 1)) +
  theme(strip.text.y = element_text(angle = 0))



bind_rows(
  d.hab.prior.e %>%
    mutate(src = 'data') %>%
    select(-workerid, -category, -metric, -val) %>%
    rename(val = avoided_endval),
  m.samp %>%
    filter(param == "mixture", chain == 3) %>%
    mutate(src = 'model') %>%
    select(-chain, -param, -type)
) %>% ggplot(., aes( x = val, lty = src, color = gender))+
  stat_ecdf()+
  facet_wrap(~item)+
  scale_color_solarized()+
  scale_x_continuous(limits = c(0,1), breaks = c(0, 0.5, 1)) +
  scale_y_continuous(limits = c(0,1), breaks = c(0, 0.5, 1)) +
  theme(strip.text.y = element_text(angle = 0))
```
