---
title: "Habituals priors"
output: html_notebook
---


```{r}
library(langcog)
library(tidyr)
library(dplyr)
library(data.table)
library(coda)
library(knitr)
library(ggthemes)
library(rwebppl)
theme_set(theme_few())
estimate_mode <- function(s) {
  d <- density(s)
  return(d$x[which.max(d$y)])
}
hdi_upper<- function(s){
  m <- HPDinterval(mcmc(s))
  return(m["var1","upper"])
}
hdi_lower<- function(s){
  m <- HPDinterval(mcmc(s))
  return(m["var1","lower"])
}
betaMean = function(a, b){
  return ( a / (a + b ))
}

betaSDev = function(a, b){
  return( sqrt ( ( a * b) / ( ( a + b ) ^ 2 * (a + b + 1) ) ) ) 
}
project.path <- "~/Documents/research/communicating-generalizations/"
data.path <- "models/habituals/data/"
model.path <- "models/habituals/"
```



## Propensity priors

Load prior data

```{r fig.height = 8, fig.width = 6}
d.hab.prior.e <- read.csv(paste(project.path, data.path, 
                      "prior2-existence.csv", sep = ""))

d.hab.prior.e <- d.hab.prior.e %>% 
  mutate(avoided_endval = ifelse(val==1, 0.999,
                                 ifelse(val==0, 0.001, val)))

# ggplot(d.hab.prior.e, aes( x= avoided_endval, fill = gender))+
#   facet_wrap(~item, scales = 'free')+
#   geom_histogram(position = position_dodge())

d.hab.prior.f <- read.csv(paste(project.path, data.path, 
                      "prior2-timesper5yr.csv", sep = "")) %>%
  mutate(log_dayRate = log(val / (365*5)),
         annualRate = val / 5)

# 
# ggplot(d.hab.prior.f, aes( x= log(val / (365*5)), fill = gender ))+
#   geom_histogram(position = position_dodge())+
#   facet_wrap(~item)
```


Raw prior data

```{r  fig.height = 8, fig.width = 6}
dh.prior <- read.csv("/Users/mht/Documents/research/habituals/data/priors/priors-2.csv")

dh.prior <- dh.prior %>%
  mutate(comparisonTime_men = as.character(comparisonTime_men),
         comparisonTime_women = as.character(comparisonTime_women)) %>%
  rowwise() %>%
  mutate(
    mixture_male = nPersons_men / comparisonNum_men,
    mixture_female = nPersons_women / comparisonNum_women,
    dayRate_male = ifelse(comparisonTime_men == "week", nInstances_men / 7,
                   ifelse(comparisonTime_men == "month", nInstances_men / 30,
                   ifelse(comparisonTime_men == "year", nInstances_men / 365,
                   ifelse(comparisonTime_men == "5 years", 
                          nInstances_men / (5*365), -99)))),
    dayRate_female = ifelse(comparisonTime_women == "week", nInstances_women / 7,
                   ifelse(comparisonTime_women == "month", nInstances_women / 30,
                   ifelse(comparisonTime_women == "year", nInstances_women / 365,
                   ifelse(comparisonTime_women == "5 years", 
                          nInstances_women / (5*365), -99)))),
    annualRate_male = dayRate_male * 365,
    annualRate_female = dayRate_female * 365
  )


dh.prior.filtered <- filter(dh.prior, 
       !(
         (mixture_male == 0) ||   (mixture_female == 0) ||   
           (dayRate_male == 0) ||   (dayRate_female == 0)  )
       )

# ggplot(dh.prior.filtered %>% 
#          select(item, starts_with("dayRate")) %>%
#          gather(key, val, -item), aes( x= log(val )))+
#   geom_histogram(position = position_dodge())+
#   facet_wrap(~item, scales = 'free')

#write.csv(dh.prior, file = paste(project.path, data.path, "prior2.csv", sep = ""))
```

Marginal distribution on frequency

```{r fig.width = 8, fig.height = 12}
dh.prior.samples <- data.frame()
for (i in 1:10){
  
  dh.prior.samples <- bind_rows(
    dh.prior.samples,
    dh.prior.filtered %>% 
    select(workerid, item, starts_with("annualRate"), 
           starts_with("mixture")) %>%
    rowwise() %>%
    mutate(
      stable_male = rbinom(n = 1, size = 1, prob = mixture_male),
       freq_male = ifelse(stable_male == 1, annualRate_male, 0.01),
       stable_female = rbinom(n = 1, size = 1, prob = mixture_female),
       freq_female = ifelse(stable_female == 1, annualRate_female, 0.01)
       ) %>%
    select(item, freq_male, freq_female) %>%
    gather(gender, val, freq_male, freq_female) %>%
  mutate(gender = gsub("freq_", "", gender))
  )
  print(i)
}

```


Density plots

```{r}
ggplot(dh.prior.samples, aes( x = log(val), fill = gender))+
  geom_density(alpha = 0.3, aes( y = ..scaled.. ))+
  facet_wrap(~item)+
  scale_fill_solarized()+
  scale_x_continuous(limits = c(-5,10)) +
  scale_y_continuous(limits = c(0,1), breaks = c(0, 0.5, 1)) +
  theme(strip.text.y = element_text(angle = 0))
```

CDFs

```{r}
ggplot(dh.prior.samples, aes( x = log(val), color = gender))+
  stat_ecdf()+
  facet_wrap(~item)+
  scale_color_solarized()+
  scale_x_continuous(limits = c(-5,10)) +
  scale_y_continuous(limits = c(0,1), breaks = c(0, 0.5, 1)) +
  theme(strip.text.y = element_text(angle = 0))
```


# BDA of prior data

```{r}
hab.prior.bda.model <- '
var betaShape = function(p){
  return {a: p.g * p.d, b: (1-p.g) * p.d}
};

var model = function(){
	var mixtureParams = {
		male: {
      g: uniformDrift({a: 0, b: 1, width: 0.2}),
      d: uniformDrift({a: 0, b: 100, width: 5})
    },
		female: {
      g: uniformDrift({a: 0, b: 1, width: 0.2}),
      d: uniformDrift({a: 0, b: 100, width: 5})
    }
	};

	var mixtureShapes = {
		male: betaShape(mixtureParams.male),
		female: betaShape(mixtureParams.female)
	};

	mapData({data: data.mixture}, function(d){
    Beta(mixtureShapes[d.gender]).score(d.val) == -Infinity ? display(JSON.stringify(d)) : null
     // display(Beta(mixtureShapes[d.gender]).score(d.val))
		observe(Beta(mixtureShapes[d.gender]), d.val)
	})

	var stableFrequency = {
		male: {
			mu: uniformDrift({a: -5, b:10, width: 2}),
			sigma: uniformDrift({a:0, b:5, width: 1})
		},
		female: {
			mu: uniformDrift({a:-5, b:10, width: 2}),
			sigma: uniformDrift({a:0, b:5, width: 1})
		}
	}

	mapData({data: data.frequency}, function(d){
    Gaussian(stableFrequency[d.gender]).score(d.logval) == -Infinity ? 
        display(JSON.stringify(d)) : null
    // display(Gaussian(stableFrequency[d.gender]).score(d.logval))
		observe(Gaussian(stableFrequency[d.gender]), d.logval)
	})

	var existenceProb = {
		male: beta(mixtureShapes.male),
		female: beta(mixtureShapes.female)
	};

	var freqWhenPresent = {
		male: gaussian(stableFrequency.male),
		female: gaussian(stableFrequency.female)
	}

  var marginalFreq = {
    male: flip(existenceProb.male) ? freqWhenPresent.male : -5,
    female: flip(existenceProb.female) ? freqWhenPresent.female : -5,
  }

  return marginalFreq
}
'
```



```{r}
items <- levels(dh.prior.filtered$item)
n_samples <- 5000
rs.bda.prior <- data.frame()

for (it in items){
  
 df.prior.toPass <- list(
   frequency = dh.prior.filtered %>%
      filter(item == it) %>%
      select(item, starts_with("annualRate")) %>%
      gather(gender, val, -item) %>%
      mutate(gender = gsub("annualRate_", "", gender),
             logval = log(val)),
   mixture = dh.prior.filtered %>% 
      filter(item == it) %>%
      select(item, starts_with("mixture")) %>%
      gather(gender, val, -item) %>%
      mutate(gender = gsub("mixture_", "", gender)) %>%
      rowwise() %>%
      mutate(val = ifelse(val == 1, 0.9999, 
                          ifelse(val == 0, 0.000001, val)))
  )
 
  rs <- webppl(program_code = hab.prior.bda.model,
       model_var = "model",
       inference_opts = list(method = "MCMC", samples = n_samples,
                             burn = n_samples / 2),
       data = df.prior.toPass,
       data_var = "data")
  
  rs.bda.prior <- bind_rows(rs.bda.prior, 
                            rs %>% mutate(item = it)
  )


}

```



Density plots

```{r fig.width = 6, fig.height = 6}
bind_rows(
  dh.prior.samples %>% 
    mutate(src = 'data', 
           val = log(val)),
  rs.bda.prior %>%
    rename(gender = Parameter, val = value) %>%
    select(-Iteration, -Chain) %>%
    mutate(src = 'model')
  ) %>%
ggplot(. , aes( x = val, fill = src, lty = src))+
  geom_density(alpha = 0.3, aes( y = ..scaled.. ))+
  facet_wrap(~item)+
  scale_fill_solarized()+
  scale_x_continuous(limits = c(-5,10)) +
  scale_y_continuous(limits = c(0,1), breaks = c(0, 0.5, 1)) +
  theme(strip.text.y = element_text(angle = 0))
```
CDFs

```{r fig.width = 6, fig.height = 6}
bind_rows(
  dh.prior.samples %>% 
    mutate(src = 'data', 
           val = log(val)),
  rs.bda.prior %>%
    rename(gender = Parameter, val = value) %>%
    select(-Iteration, -Chain) %>%
    mutate(src = 'model')
  ) %>%
ggplot(. , aes( x = val, color = src, lty = src))+
  stat_ecdf()+
  facet_wrap(~item)+
  scale_color_solarized()+
  scale_x_continuous(limits = c(-5,10)) +
  scale_y_continuous(limits = c(0,1), breaks = c(0, 0.5, 1)) +
  theme(strip.text.y = element_text(angle = 0))
```

## Friends and family

```{r}
df.ff.future <- read.csv(paste(project.path, "data/habituals/priors/friends-and-family-2-trials.csv", sep= ""))

df.ff.past <- read.csv(paste(project.path, "data/habituals/priors/friends-and-family-3-trials.csv", sep= ""))
```


```{r}
annualRates = list("5 years" = 1/5, "2 years" = 1/2,
                   "year" = 1, "6 months" = 2, "2 months" = 6,
                   "month" = 12, "2 weeks" = 26 ,"week" = 52)

df.ff.future <- df.ff.future %>%
  rowwise() %>%
  mutate(annualRate = annualRates[[as.character(interval)]]*n_times,
         logAnnualRate = ifelse(annualRate == 0, -5, log(annualRate)))


df.tidy.13 <- bind_rows(
  df.tidy %>% 
    mutate(src = 'future'),
  df3.tidy %>% 
    mutate(src = 'past')
  ) %>%
    mutate(annualRate = ifelse(annualRate == 0, 0.05, annualRate),
           logAnnual  = log(annualRate))

```

```{r}
hab.prior.ff.bda.model <- '
var model = function(){

	var theta = uniformDrift({a: 0, b: 1, width: 0.1});

	var priorParams = {
		mu: uniformDrift({a: -2.5, b: 9, width: 0.5}),
		sigma: uniformDrift({a: 0, b: 10, width: 0.5})
	}

	mapData({data: data}, function(d){
		var scr = util.logsumexp([
			 Math.log(theta) + Gaussian(priorParams).score(d.logAnnualRate),
			 Math.log(1- theta) + Delta({v: -5}).score(d.logAnnualRate)
		 ])
		 // display(scr)
		 factor(scr)
	})

  var marginalFreq = flip(theta) ? gaussian(priorParams) : -5

  return marginalFreq
}
'
```

```{r}
items <- levels(dh.prior.filtered$item)
n_samples <- 500
rs.bda.prior.ff <- data.frame()

for (it in items){
  
 df.prior.toPass <- df.ff.future %>%
   filter(action == it) %>%
   select(logAnnualRate)

  rs <- webppl(program_code = hab.prior.ff.bda.model,
       model_var = "model",
       inference_opts = list(method = "MCMC", 
                             samples = n_samples,
                             burn = n_samples / 2,
                             verbose = T),
       data = df.prior.toPass,
       data_var = "data")
  
  rs.bda.prior.ff <- bind_rows(
    rs.bda.prior.ff, 
    rs %>% mutate(item = it)
  )

  print(it)
  
}

```
