---
title: "Model comparison using Log-likelihoods / Bayes Factors"
output: html_notebook
---
```{r}
knitr::opts_chunk$set(echo=FALSE, warning=FALSE, message=FALSE)
```


```{r}
library(langcog)
library(tidyr)
library(dplyr)
library(data.table)
library(coda)
library(knitr)
library(ggthemes)
library(rwebppl)
theme_set(theme_few())
estimate_mode <- function(s) {
  d <- density(s)
  return(d$x[which.max(d$y)])
}
hdi_upper<- function(s){
  m <- HPDinterval(mcmc(s))
  return(m["var1","upper"])
}
hdi_lower<- function(s){
  m <- HPDinterval(mcmc(s))
  return(m["var1","lower"])
}
betaMean = function(a, b){
  return ( a / (a + b ))
}

betaSDev = function(a, b){
  return( sqrt ( ( a * b) / ( ( a + b ) ^ 2 * (a + b + 1) ) ) ) 
}
project.path <- "~/Documents/research/communicating-generalizations/"
data.path <- "models/habituals/data/"
model.path <- "models/habituals/model_comparison/"
```



```{r}
# n_chains <- 3
# n_samples <- 500000
# burn <- n_samples / 2
# lag <- 50


n_chains <- 2
#model1_prefix <- "logLikelihood-habituals-S2-ffPrior2Structured-silenceAlt-"
model1_prefix <- "logLikelihood-habituals-regression-intercept-freq-priorMean-narrowPriors-ffPrior2Structured-"
n_samples1 <- 1000000
burn1 <- n_samples1 / 2
lag1 <- 100
# 

# model1_prefix <- "logLikelihood-habituals-S2-ffPrior2Structured-silenceAlt-"
# n_samples1 <- 100000
# burn1 <- n_samples1 / 2
# lag1 <- 10
# 
# 

model2_prefix <- "logLikelihood-habituals-S1-ffPrior2Structured-silenceAlt-"
n_samples2 <- 500000
burn2 <- n_samples2 / 2
lag2 <- 50




m.samp.1 <- data.frame()
m.samp.2 <- data.frame()
for (i in seq(1, n_chains)){
  
  mi.1 <- fread(paste(project.path, model.path,
                    "results/",
                    model1_prefix, n_samples1, "_burn", burn1, "_lag", lag1,
                    "_chain", i, ".csv", sep = ""))
  m.samp.1.i <- mi.1 %>% mutate(chain = i)
  m.samp.1 <- bind_rows(m.samp.1, m.samp.1.i)

  
  mi.2 <- fread(paste(project.path, model.path,
                    "results/",
                    model2_prefix, n_samples2, "_burn", burn2, "_lag", lag2,
                    "_chain", i, ".csv", sep = ""))
  m.samp.2.i <- mi.2 %>% mutate(chain = i)
  m.samp.2 <- bind_rows(m.samp.2, m.samp.2.i)  
  
  
  print(i)
}

# i = 1
# 
# m.samp.1 <- fread(paste(project.path, model.path,
#                   "results/",
#                   model1_prefix, n_samples, "_burn", burn, "_lag", lag1,
#                   "_chain", i, ".csv", sep = ""))
# 
# m.samp.2 <- fread(paste(project.path, model.path,
#                   "results/",
#                   model2_prefix, n_samples, "_burn", burn, "_lag", lag2,
#                   "_chain", i, ".csv", sep = ""))

m.samp.2[is.na(m.samp.2$cat), "cat"] <- "s1"

m.ll <- bind_rows(
    m.samp.1 %>% filter(type == "logLikelihood"),
    m.samp.2 %>% filter(type == "logLikelihood")
  )

```


Convergence?

Log-likelihoods by iteration

```{r}
m.ll.i <- m.ll %>% 
  filter(type == "logLikelihood") %>% 
  mutate(item = paste(type, item, cat, chain, sep = "_")) %>%
  select(-type, -cat, -param, -gender, -chain) %>%
  group_by(item) %>%
  mutate(iteration = ave(item == item, item, FUN = cumsum)) %>%
  separate(item, into = c("type", "action", "src", "chain"), sep = "_")


m.ll.i %>%
  group_by(iteration, src, chain) %>%
  summarize(ll = sum(val)) %>%
  filter((iteration %% 100) == 0) %>%
  ggplot(., aes( x = iteration, y = ll, color = chain, lty = src))+
  geom_line()
```

Cumulative (running) average log likelihoods

```{r}
m.ll.i %>%
  group_by(src, chain, iteration) %>% 
  summarize(loglik_i = sum(val)) %>%
  group_by(src, chain) %>%
  mutate(cs = cumsum(loglik_i) / iteration) %>%
  filter((iteration %% 100) == 0) %>%
  ggplot(., aes( x = iteration, y = cs, color = chain, lty = src))+
  geom_line()
```

Bayes Factor by iteration

```{r}
m.ll.i %>%
  group_by(iteration, src, chain) %>%
  summarize(ll = sum(val)) %>%
  ungroup() %>%
  group_by(iteration, chain)
  filter((iteration %% 100) == 0) %>%
  ggplot(., aes( x = iteration, y = ll, color = chain, lty = src))+
  geom_line()
```


### Frequency prior parameters (posterior)

```{r fig.width = 8, fig.height = 12}
m.samp %>% 
  filter(type == "prior", cat  != "postPred") %>%
  ggplot(., aes( x = val, fill = cat))+
  geom_histogram()+
  facet_grid(item ~ cat, scales = 'free') +
  theme(strip.text.y = element_text(angle = 0))  
```


### Average log-likelihood by item

```{r}

m.ll.item.summary <- m.ll %>%
  group_by(item, cat, chain) %>%
  summarize(MAP = estimate_mode(val),
            cred_upper = hdi_upper(val), cred_lower = hdi_lower(val)) %>%
  ungroup() %>% 
  mutate(item = factor(item, levels = item[order(MAP)]))

ggplot(m.ll.item.summary, 
       aes(x = item, y = MAP, ymin = cred_lower, ymax = cred_upper, fill = cat))+
  geom_bar(stat = 'identity', position = position_dodge(), alpha = 0.5, color = 'black')+
  #geom_errorbar(position = position_dodge())+
  theme(axis.text.x = element_text(angle = 90))+
  coord_flip() + 
  facet_wrap(~chain)
```


```{r}
m.ll.expectation <- m.ll %>%
  #filter(!(val == -Inf)) %>%
  group_by(cat, chain) %>%
  summarize(expval = mean(val))
```

```{r}
m.ll.expectation <- m.ll.i %>%
  group_by(src, chain, iteration) %>%
  summarize(sum_loglik = sum(val)) %>%
  ungroup() %>%
  group_by(src, chain) %>%
  summarize(expval = mean(sum_loglik))
```



