---
title: "Habituals regression alternative model"
output: html_notebook
---

```{r}
knitr::opts_chunk$set(echo=FALSE, warning=FALSE, message=FALSE)
```


```{r}
library(langcog)
library(tidyr)
library(dplyr)
library(data.table)
library(coda)
library(knitr)
library(ggthemes)
library(rwebppl)
theme_set(theme_few())
estimate_mode <- function(s) {
  d <- density(s)
  return(d$x[which.max(d$y)])
}
hdi_upper<- function(s){
  m <- HPDinterval(mcmc(s))
  return(m["var1","upper"])
}
hdi_lower<- function(s){
  m <- HPDinterval(mcmc(s))
  return(m["var1","lower"])
}
project.path <- "~/Documents/research/communicating-generalizations/"
data.path <- "models/habituals/data/"
model.path <- "models/habituals/"
```

Load truth judgment data

```{r}
d.hab <- read.csv(paste(project.path, data.path, 
                    "tj-2-logtimes.csv", sep = ""))

d.hab.summary <- d.hab %>% 
  mutate(response = ifelse(response == "agree-key", 1, 0),
         roundedFreq = round(log_times * 2) / 2) %>%
  group_by(habitual, time_period, log_times, roundedFreq) %>%
  multi_boot_standard(column = "response")
```


```{r}
# n_chains <- 3
# n_samples <- 500000
# burn <- n_samples / 2
# lag <- 50


model_prefix <- "posterior-regression-intercept-freq-priorMean-ffPrior2Structured-"
n_samples <- 10000
burn <- n_samples / 2
lag <- 10

# m.samp <- data.frame()
# for (i in seq(1, n_chains)){
#   mi <- fread(paste(project.path, model.path,
#                     "results/",
#                     model_prefix, n_samples, "_burn", burn, "_lag", lag,
#                     "_chain", i, ".csv", sep = ""))
# 
#   m.samp.i <- mi %>% mutate(chain = i)# %>% get_samples(., num_samples = n_samples - burn)
#   m.samp <- bind_rows(m.samp, m.samp.i)
#   print(i)
# }

i = 1

m.samp <- fread(paste(project.path, model.path,
                  "results/",
                  model_prefix, n_samples, "_burn", burn, "_lag", lag,
                  "_chain", i, ".csv", sep = ""))
```

### Regression parameter posteriors

```{r}
m.samp %>% 
  filter(type == "param") %>% 
  ggplot(., aes(x = val))+
  geom_histogram(position = position_dodge())+
  facet_wrap(~ item + cat, scales = 'free')
```

### Frequency prior parameters (posterior)


```{r fig.width = 8, fig.height = 12}
m.samp %>% 
    filter(type == "prior", cat  != "postPred") %>%
  ggplot(., aes( x = val, fill = cat))+
  geom_histogram()+
  facet_grid(item ~ cat, scales = 'free') +
  theme(strip.text.y = element_text(angle = 0))  
```



### Posterior predictive truth judgments

```{r}
m.pp <- m.samp %>%
  filter(type == "predictive") %>%
  rename(habitual = item, 
         time_period = param) %>% 
  group_by(habitual, time_period) %>%
  summarize(MAP = estimate_mode(val),
            cred_upper = hdi_upper(val),
            cred_lower = hdi_lower(val))

md <- left_join(m.pp, d.hab.summary %>% ungroup())
```

```{r}
ggplot(md, aes(x = MAP, xmin = cred_lower, xmax = cred_upper,
               y = mean, ymin = ci_lower, ymax = ci_upper))+
  geom_point()+
  xlim(0, 1)+
  ylim(0, 1)+
  geom_abline(intercept = 0, slope = 1, lty = 3)+
  geom_errorbar(alpha = 0.3)+
  geom_errorbarh(alpha = 0.3)+
  coord_fixed()
```

